/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos;
import javax.swing.*;
import java.awt.*;
import javax.swing.JOptionPane;
import pos.Cashier_Dashboard.search;

/**
 *
 * @author Supun
 */
public class Product_Selection extends javax.swing.JPanel {

    /**
     * Creates new form Product_Selection
     */
    
    public class frontdata{
        public static String[] arr = new String[100];
        public static int[] selctedqty = new int[100];
    }
    
    public Product_Selection() {
        initComponents();
        search_results();
    }
    
    private void search_results() {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS)); // To arrange components vertically
       
            JLabel label = new JLabel(search.sre);
            label.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
              for(int i = 0; i < 100; i++){
                if(frontdata.arr[i] == null){
                   frontdata.arr[i] = label.getText();
                   String userInput = JOptionPane.showInputDialog(null, "Enter Quantity");
                   frontdata.selctedqty[i] = Integer.parseInt(userInput);
                   break;
                }  
              }      
                Cashier_Dashboard cashier = new Cashier_Dashboard();
                cashier.setTitle("Super Mart");
                cashier.setSize(906, 694);
                cashier.setVisible(true);
                java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(panel);
                if (parentWindow != null) {
                    parentWindow.dispose();
                }
            }
        });
           panel.add(label);
       
        
        // Add the created panel to the current JPanel
        this.setLayout(new BorderLayout()); // Ensure you have a layout to position components
        this.add(panel, BorderLayout.CENTER);

        // Revalidate and repaint to ensure UI updates
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
